# Generated by Django 3.2.8 on 2021-12-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    #operations = [
        #migrations.AddField(
        #    model_name='diary',
        #    name='photo2',
        #    field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真2'),
        #),
        #migrations.AddField(
        #    model_name='diary',
        #    name='photo3',
        #    field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真3'),
        #),
    #]
